url: http://blog.poormansmath.net
name: The poor man's math blog
description: By Stefano Maggiolo
avatar: https://a.disquscdn.com/uploads/users/12609/6142/avatar92.jpg?1413534504

footer-links:
  email: ste@poormansmath.net
  twitter: zzzviad
  github: stefano-maggiolo
  googleplus: +StefanoMaggiolo
  rss: rss

disqus: poormansmath
google_analytics: UA-2077547-5

markdown: kramdown
highlighter: pygments
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.1.0

sass:
  style: :compressed

plugins:
  - jekyll-sitemap

excerpt_separator: <!--more-->

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
